# Generated by Django 5.1.5 on 2025-10-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new_release',
        ),
    ]
