# Generated by Django 5.1.5 on 2025-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimage_color_remove_productsize_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Hoodie', 'Hoodie'), ('Pants', 'Pants'), ('Socks', 'Socks'), ('T-Shirt', 'T-Shirt'), ('Accessory', 'Accessory')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10),
        ),
    ]
